spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/teentime
    username: sa
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
      # show_sql: true
      format_sql: true
  config:
    activate:
      on-profile: test

server:
  port: 8080